version: "3.9"
services:
     base:
          build: images/base
          environment: 
               - USER=docker
     pillar:
          build: images/pillar
          environment: 
               - USER=docker
     lidars:
          network_mode: host
          build: 
               context: packages/perception/velodyne_nodes
               dockerfile: ../../../images/frame/Dockerfile
          environment: 
               - USER=docker
               - package_name=vt_velodyne_nodes
               - param_name=vlp16_voltron_front.param.yaml
          volumes:
               - type: bind
                 source: ./params
                 target: /opt/params
     lidar_filters:
          network_mode: host
          build: 
               context: packages/perception/point_cloud_filter_transform_nodes
               dockerfile: ../../../images/frame/Dockerfile
          environment: 
               - USER=docker
               - package_name=vt_point_cloud_filter_transform_nodes
               - param_name=pc_filter_transform_front_sim.param.yaml
          volumes:
               - type: bind
                 source: ./params
                 target: /opt/params
     
