version: "3.9"
services:
     base:
          build: images/base
          environment: 
               - USER=docker
     pillar:
          build: images/pillar
          environment: 
               - USER=docker
     lidar_front:
          network_mode: host
          build: 
               context: packages/perception/velodyne_nodes
               dockerfile: ../../../images/frame/Dockerfile
          environment: 
               - USER=docker
               - package_name=vt_velodyne_nodes
