# param/robot_localization.param.yaml
---
/**:
  ros__parameters:

    # Future iterations of Hubble will include data from speedometer,
    # IMUs, and Lidar odometry (NDT).

    frequency: 100.0 # Estimate update frequency, Hz, double
    world_frame: "map"

    odom0: "/odom0"
    odom0_config: [true, true, true, false, false, true,
                   false, false, false, false, false, false,
                   false, false, false]