# Templated from Autoware drivers/velodyne_nodes/param/test.param.yaml
/**:
  ros__parameters:
    ip: "192.168.1.100"
    port: 2368
    cloud_size:  55000
    topic: "points_raw"  # UdpDriverNode strictly expects to get the topic via `declare_parameter`.
    frame_id: "lidar_rear"
    timeout_ms: 10
    rpm:        600
