pcl_localization:
  ros__parameters:
    registration_method: "NDT"
    ndt_resolution: 2.0
    ndt_step_size: 0.3
    trans_epsilon: 0.01
    max_iterations: 35
    voxel_leaf_size: 0.4
    scan_max_range: 70.0
    scan_min_range: 1.0
    scan_period: 0.1
    use_pcd_map: false
    map_path: "/home/wheitman/navigator-2/data/maps/grand_loop/grand_loop.pcd"
    set_initial_pose: false
    initial_pose_x: -213.24679565429688
    initial_pose_y: -310.8988037109375
    initial_pose_z: -0.0029020091934057746
    initial_pose_qx: 0.0
    initial_pose_qy: 0.0
    initial_pose_qz: -0.9870872938169499
    initial_pose_qw: 0.16018325251139845
    use_odom: true
    use_imu: false
    enable_debug: false
    fitness_gnss_threshold: 15.0
    dist_gnss_threshold: 50.0
    enable_logging_to_file: true
    pose_position_cov_k: 40.0
