pcl_localization:
  ros__parameters:
    registration_method: "NDT"
    ndt_resolution: 2.0
    ndt_step_size: 0.2
    trans_epsilon: 0.01
    max_iterations: 35
    voxel_leaf_size: 0.4
    scan_max_range: 100.0
    scan_min_range: 1.0
    scan_period: 0.1
    use_pcd_map: false
    map_path: "/home/wheitman/navigator-2/data/maps/grand_loop/grand_loop.pcd"
    set_initial_pose: true
    initial_pose_x: -173.2391822215378
    initial_pose_y: 29.10477333449926
    initial_pose_z: -0.0029020091934057746
    initial_pose_qx: 0.0
    initial_pose_qy: 0.0
    initial_pose_qz: 0.6853907477913105
    initial_pose_qw: 0.7281754753093983
    use_odom: true
    use_imu: false
    enable_debug: true
    fitness_gnss_threshold: 55.0
    dist_gnss_threshold: 5.0
    enable_logging_to_file: true
