pcl_localization:
  ros__parameters:
    use_pcd_map: true
    map_path: "data/maps/grand_loop/grand_loop.pcd"
    registration_method: "NDT"
    ndt_resolution: 2.0
    ndt_step_size: 0.01
    transform_epsilon: 0.01
    voxel_leaf_size: 1.0
    scan_max_range: 100.0
    scan_min_range: 10.0
    set_initial_pose: false
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_z: 0.0
    initial_pose_qx: 0.0
    initial_pose_qy: 0.0
    initial_pose_qz: 0.0
    initial_pose_qw: 1.0
    use_imu: true
    enable_debug: true
    gps_dist_recenter_threshold: 5.0
