/**:
  ros__parameters:
    cruising_speed_ms: 10.0
    map_xodr_file_path: data/maps/grand_loop/grand_loop.xodr
    route_info_params: [
      "66", "-1", "0",
      "359", "-1", "0",
      "85", "-1", "0"
    ]
    # route_info_params: [
    #   # "32", "-1", "60.41",
    #   # "200", "-1", "0",
    #   # "36", "-1", "0",
    #   # "36", "-1", "28.02",
    #   # "36", "-1", "36.72",
    #   # "36", "-2", "57.08",
    #   "36", "-2", "68.19",
    #   "597", "-1", "0",
    #   "68", "-1", "0",
    #   "86", "-1", "0",
    #   "87", "-2", "0",
    #   "344", "-1", "0",
    #   "45", "1", "0",
    #   "266", "1", "0",
    #   "43", "1", "0",
    #   "467", "1", "0",
    #   "16", "-1", "0",
    # ]