/**:
  ros__parameters:
    cruising_speed_ms: 10.0
    map_xodr_file_path: data/maps/grand_loop/grand_loop.xodr
    route_info_params: [
      "78", "-1", "0",
      "1463", "-1", "0",
      "100", "-1", "0",
      "318", "-1", "0",
      "38", "-1", "0",
      "669", "-1", "0",
      "7", "-1", "0",
      "7", "-1", "29.77",
      "7", "-1", "34.99",
      "355", "-1", "0",
      "62", "-1", "0",
      "1259", "-1", "0",
      "93", "4", "81.71",
      "93", "5", "58.75",
      "93", "6", "52.15",
      "93", "5", "2.33",
      "93", "5", "0",
      "480", "1", "0",
      "42", "-1", "0",
      "42", "-1", "61.41",
      "1300", "-1", "0",
      "47", "-1", "0",
      "47", "-1", "17.07",
      "47", "-1", "25.77",
      "47", "-2", "46.13",
      "47", "-2", "57.24",
      "255", "-1", "0",
      "81", "-1", "0",
      "105", "-1", "0",
      "1396", "-1", "0",
      "106", "-1", "0",
      "106", "-2", "106.56",
      "202", "-2", "0",
      "108", "-2", "0",
      "486", "-1", "0",
      "56", "1", "0",
      "1325", "1", "0",
      "54", "1", "262.03",
      "54", "1", "0",
      "1271", "1", "0",
      "17", "-1", "0",
      "1187", "-1", "0",
      "18", "-1", "0",
      "1430", "-1", "0",
      "19", "-1", "0",
      "236", "-1", "0",
      "80", "-3", "0",
      "27", "-3", "0",
      "0", "-3", "0",
      "126", "-1", "0",
      "41", "-1", "0",
      "20", "1", "4.49",
      "20", "1", "4.03",
      "20", "1", "0",
      "76", "1", "0",
      "368", "1", "0",
      "75", "1", "0",
      "132", "1", "0",
      "115", "-1", "0",
      "115", "-1", "81.15",
      "1419", "-1", "0",
      "72", "1", "35.03",
      "72", "2", "0",
      "424", "1", "0",
      "98", "-1", "0",
      "1154", "-1", "0",
      "39", "1", "0"
    ]