/**:
  ros__parameters:
    cruising_speed_ms: 10.0
    map_xodr_file_path: data/maps/grand_loop/grand_loop.xodr
    route_info_params: [
      "92", "4", "81.70",
      "92", "5", "58.74",
      "92", "6", "52.14",
      "92", "5", "2.32",
      "92", "5", "0",
      "417", "1", "0",
      "42", "-1", "0",
      "42", "-1", "59.74",
      "42", "-1", "210.72",
      "42", "-1", "219.42",
      "42", "-1", "239.78",
      "42", "-1", "250.89",
      "203", "-1", "0",
      "80", "-1", "0",
      "102", "-1", "0",
      "102", "-2", "265.34",
      "422", "-1", "0",
      "53", "1", "267.07",
      "53", "1", "0",
      "785", "1", "0",
      "17", "-1", "0",
      "688", "-1", "0",
      "18", "-1", "0",
      "824", "-1", "0",
      "19", "-1", "0"
    ]