/**:
  ros__parameters:
    cruising_speed_ms: 10.0
    map_xodr_file_path: data/maps/grand_loop/grand_loop.xodr
    route_info_params: [
      "81", "-1", "0",
      "953", "-1", "0",
      "82", "-1", "0",
      "919", "-1", "0",
      "105", "-1", "0",
      "332", "-1", "0",
      "39", "-1", "0",
      "663", "-1", "0",
      "78", "-1", "0",
      "337", "-1", "0",
      "7", "-1", "0",
      "465", "-1", "0",
      "63", "-1", "0",
      "776", "-1", "0",
      "98", "4", "82.99",
      "98", "5", "60.03",
      "98", "6", "53.43",
      "98", "5", "3.61",
      "98", "5", "0",
      "582", "1", "0",
      "98", "5", "0",
      "43", "-1", "0",
      "43", "-1", "59.72",
      "898", "-1", "0",
      "48", "-1", "0",
      "48", "-1", "20.06",
      "48", "-1", "28.76",
      "48", "-2", "49.12",
      "48", "-2", "60.23",
      "262", "-1", "0",
      "86", "-1", "0",
      "998", "-1", "0",
      "110", "-1", "0",
      "689", "-1", "0",
      "111", "-1", "0",
      "219", "-2", "0",
      "113", "-2", "0",
      "609", "-1", "0",
      "57", "1", "0",
      "390", "1", "0",
      "55", "1", "263.97",
      "55", "1", "0",
      "788", "1", "0",
      "17", "-1", "0",
      "181", "-1", "0",
      "18", "-1", "0",
      "275", "-1", "0",
      "19", "-1", "0",
      "814", "-1", "0",
      "809", "-1", "0",
      "83", "-3", "0",
      "28", "-3", "0",
      "0", "-3", "0",
      "150", "-1", "0",
      "42", "-1", "0",
      "21", "1", "0",
      "80", "1", "0",
      "497", "1", "0",
      "79", "1", "0",
      "960", "1", "0",
      "120", "-1", "0",
      "120", "-1", "67.88",
      "75", "1", "38.16",
      "75", "2", "0",
      "827", "1", "0",
      "103", "-1", "0",
      "141", "-1", "0",
      "40", "1", "0",
      "955", "1", "0",
      "81", "1", "0"
    ]