# Automatically build and test all packages in our workspace
name: Build and Test

on:
  pull_request:
    branches: [ main, dev ]

  # Allows manual starting of the workflow
  workflow_dispatch:

jobs:
  container-test-job:
    runs-on: [self-hosted]
    container:
      image: novautd/navigator:latest
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - uses: actions/checkout@v2
      - name: Try building with Docker
        run: "cd $GITHUB_WORKSPACE && colcon build --packages-select cyclonedds --cmake-clean-cache && . install/setup.bash && colcon build --cmake-clean-cache