# Automatically build and test all packages in our workspace
name: Build and Test

on:
  pull_request:
    branches: [ main, dev ]

  # Allows manual starting of the workflow
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: [self-hosted]
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Enter Workspace
        run: |
          cd $GITHUB_WORKSPACE
          echo Workspace directory: $(pwd)

      - name: Build Navigator using latest Docker image
        run: /bin/bash docker/build_container.bash